include:
  - board: eyelash_nano
    shield: eyelash_corne_right nice_view_gem
  - board: eyelash_nano
    shield: eyelash_corne_left nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_nano
    shield: settings_reset
